>>> #  **6.7 学习报告**
>>>  ## 一、异常
>>>  *笔记：在程序执行过程中发生的任何错误都是异常。每个异常显示一些相关的错误信息，* 
>>> ![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid1080407-20190608-1559995934923)
>>>
>>> ## 1.NameError 
>>> 当访问一个未定义的变量则会发生 NameError；
>>> TypeError 也是一种经常出现的异常。当操作或函数应用于不适当类型的对象时引发
>>> ![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid1080407-20190608-1559996658694)
>>>
>>> ## 2.处理异常
>>>  *笔记* 
>>>  *使用 try...except 块来处理任意异常。基本的语法像这样：
>>>
>>> try:
>>>     statements to be inside try clause
>>>     statement2
>>>     statement3
>>>     ...
>>> except ExceptionName:
>>>     statements to evaluated in case of ExceptionName happens
>>> * 
>>>    *它以如下方式工作：
>>>
>>>     首先，执行 try 子句 （在 try 和 except 关键字之间的部分）。
>>>
>>>     如果没有异常发生，except 子句 在 try 语句执行完毕后就被忽略了。
>>>
>>>     如果在 try 子句执行过程中发生了异常，那么该子句其余的部分就会被忽略。
>>>
>>>     如果异常匹配于 except 关键字后面指定的异常类型，就执行对应的 except 子句。然后继续执行 try 语句之后的代码。
>>>
>>>     如果发生了一个异常，在 except 子句中没有与之匹配的分支，它就会传递到上一级 try 语句中。
>>>
>>>     如果最终仍找不到对应的处理语句，它就成为一个 未处理异常，终止程序运行，显示提示信息。
>>> * 
>>>   ![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid1080407-20190608-1559997405257)
>>>
>>> ## 3.抛出异常
>>> ![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid1080407-20190608-1559997797640)
>>>
>>> ## 4.定义清理行为
>>> ![图片描述](https://dn-simplecloud.shiyanlou.com/courses/uid1080407-20190608-1559998148260)